events {
    worker_connections 1024;
}

stream {
    resolver 127.0.0.11 valid=30s ipv6=off;

    map $ssl_preread_protocol $backend {
        ""      opencloud-redirect:80;
        default opencloud:9200;
    }

    server {
        listen 9200;
        ssl_preread on;
        proxy_pass $backend;
    }
}
